### ISSUE TITLE
Can this run on Windows? - help wanted/question

### ISSUE THREAD

**Issue by adz7** [dell/libsmbios#30]
I'm wanting to get these tools working: https://github.com/dell/libsmbios/tree/master/src/libsmbios_c

Problem is the readme doesn't give much help for people who have no idea about Linux or even GitHub.  I have zero clue as to what a tarball or dependency is.  I'm running Windows Server 2012R2 and it's a Dell machine I'm having BIOS issues with.

I've managed to download Github "PortableGit-2.15.0-64-bit" to try and get started.  I have downloaded the code and have managed to navigate to the source folder but how to get the tools running is beyond me.  Could someone give me some direction from there?

**Comment by superm1** [comment]
The tools started to get ported to Windows, but this process was not completed.  I don't believe these tools will be of much help to you.  Are you running on a client machine or server?  It's just unclear because you can still run a server OS SKU on a client box.
I would recommend for Windows use use the Dell Command suite on client machines: http://en.community.dell.com/techcenter/enterprise-client/w/wiki/7431.dell-client-command-suite
On server you should use OpenManage:
http://en.community.dell.com/techcenter/systems-management/w/wiki

**Comment by superm1** [comment]
If you've got further questions, please feel free to open a thread at the Dell forums.
